controller_manager:
  ros__parameters:
    update_rate: 100

    position_controller:
      type: position_controllers/JointGroupPositionController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - base_blade_joint
    open_loop_control: true

diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      ["base_front_left_wheel_joint", "base_rear_left_wheel_joint"]
    right_wheel_names:
      ["base_front_right_wheel_joint", "base_rear_right_wheel_joint"]
    wheel_separation: 0.5
    wheel_radius: 0.15
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    open_loop: true
    velocity_rolling_window_size: 2
    enable_odom_tf: false
    use_stamped_vel: false
    position_feedback: true
