rtabmap:
  ros__parameters:
    Grid/CellSize: "0.035"
    Grid/MaxGroundAngle: "10"
    Grid/Sensor: "2"
    Grid/RangeMin: "0.7"
    Grid/RangeMax: "6.0"
    Grid/MaxObstacleHeight: "0.6"
    Grid/RayTracing: "true"
    Reg/Force3DoF: "true"
    Reg/Strategy: "2"
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityByTime: "true"
    RGBD/ProximityAngle: "70"
    RGBD/ProximityDistance: "0.5"
    RGBD/ProximityPathMaxNeighbors: "50"
    RGBD/LoopClosure: "true"
    RGBD/LoopClosureMaxDistance: "3.0"
    RGBD/LoopClosureReextractFeatures: "true"
    RGBD/MaxLoopClosureDistance: "0.15"
    RGBD/NewMapOdomChangeDistance: "0.5"
    RGBD/OdomVarianceGuess: "false"
    RGBD/OdomCorrection: "true"
    RGBD/ProximityOdomGuess: "false"
    RGBD/OptimizeMaxError: "0.1"
    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/StartAtOrigin: "true"
    RGBD/LinearUpdate: "0.2"
    RGBD/AngularUpdate: "0.3"
    RGBD/LinearSpeedUpdate: "0.05"
    RGBD/AngularSpeedUpdate: "0.02"
    RGBD/CreateOccupancyGrid: "true"
    RGBD/MarkerDetection: "true"
    Marker/Dictionary: "20"
    Marker/Length: "0.3125"
    Rtabmap/StartNewMapOnLoopClosure: "true"
    Rtabmap/DetectionRate: "30"
    Vis/Odom: "true"
    Vis/MinInliers: "35"
    Vis/InlierDistance: "0.05"
    Vis/MaxFeatures: "7000"
    Vis/EstimationType: "0"
    Vis/MaxDepth: "5"
    Vis/CorNNType: "1"
    Icp/VoxelSize: "0.02"
    Icp/PointToPlane: "true"
    Icp/PointToPlaneRadius: "0.0"
    Icp/PointToPlaneK: "20"
    Icp/CorrespondenceRatio: "0.3"
    Icp/PMOutlierRatio: "0.65"
    Icp/Epsilon: "0.0013"
    Icp/MaxCorrespondenceDistance: "0.05"
    Optimizer/Strategy: "2"
    Odom/Strategy: "0"
    Odom/FilteringStrategy: "1"
    Odom/KalmanProcessNoise: "0.001"
    Odom/KalmanMeasurementNoise: "0.01"
    Odom/GuessMotion: "true"
    Odom/GuessSmoothingDelay: "0.1"
